In [1]:
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action="ignore", category=FutureWarning)

In [2]:
from utils import setup
from indicators import  compute_indicators

In [3]:
attack,model,dataloader = setup(num_samples=1,
                                n_batches=1,
                                num_steps=5,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Gowal2021Improving_R18_ddpm_100m",
                                dataset_name="cifar10",
                                threat_model="Linf")
ds = compute_indicators(attack,model,dataloader)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

no surrogate

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,1.0,False,0.003759,False,1.0,None,0.0

In [4]:
attack,model,dataloader = setup(num_samples=20,
                                n_batches=2,
                                num_steps=5,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Gowal2021Improving_R18_ddpm_100m",
                                dataset_name="cifar10",
                                threat_model="Linf")
ds = compute_indicators(attack,model,dataloader)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

no surrogate

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,0.7,False,0.020552,False,1.0,None,0.4

In [5]:
attack, model, dataloader = setup(num_samples=1,
                                  n_batches=1,
                                  num_steps=50,
                                  step_size=4 / 255,
                                  epsilon=8 / 255,
                                  model="Gowal2021Improving_R18_ddpm_100m",
                                  dataset_name="cifar10",
                                  threat_model="Linf")
ds = compute_indicators(attack, model, dataloader)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

no surrogate

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,1.0,False,0.00319,False,0.0,None,0.0

In [6]:
attack,model,dataloader = setup(num_samples=20,
                                n_batches=2,
                                num_steps=50,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Gowal2021Improving_R18_ddpm_100m",
                                dataset_name="cifar10",
                                threat_model="Linf")
ds = compute_indicators(attack,model,dataloader)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

no surrogate

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,0.65,False,0.019787,False,0.0,None,0.0